# Adapted from:
# https://github.com/gabime/spdlog
clone_folder: c:\projects\source

branches:
  only:
    - master
    - development

environment:
  matrix:
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #- GENERATOR: '"Visual Studio 15 2017 Win64"'
    #  BUILD_TYPE: Release
    #  BUILD_SHARED: 'ON'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: '"Visual Studio 16 2019"'
      BUILD_TYPE: Debug
      BUILD_SHARED: 'OFF'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - GENERATOR: '"Visual Studio 16 2019"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #- GENERATOR: '"Visual Studio 16 2019"'
    #  BUILD_TYPE: Release
    #  BUILD_SHARED: 'ON'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build_script:
  - cmd: >-
      mkdir build

      cd build

      cmake c:\projects\source -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCSYS_BUILD_SHARED=%BUILD_SHARED% -DCSYS_BUILD_EXAMPLES=ON -DCSYS_BUILD_TESTS=ON -DCSYS_BUILD_WARNINGS=ON

      cmake --build . --config %BUILD_TYPE%

before_test:
  - set PATH=%PATH%;C:\projects\source\build\%BUILD_TYPE%

# ENABLE TO ACTIVA APPVEYOR REMOTE DESKTOP
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - C:\projects\source\build\tests\%BUILD_TYPE%\csys_tests.exe